// Firefox popup script - adapted to use browser/chrome APIs interchangeably
(function(){
  const api = typeof browser !== 'undefined' ? browser : chrome;
  let currentFilter = 'all'; let streams = []; let searchQuery = '';
  async function getCurrentTab(){ const tabs = await api.tabs.query({ active:true, currentWindow:true }); return tabs[0]; }
  async function loadStreams(){ const tab = await getCurrentTab(); const resp = await api.runtime.sendMessage({ action:'getStreams', tabId: tab.id }); streams = resp.streams || []; renderStreams(); }
  function renderStreams(){ const container = document.getElementById('streams-list'); const countEl = document.getElementById('stream-count'); let filtered = streams.filter(s => currentFilter==='all' ? true : (currentFilter==='drm'? s.isDRM : s.type.includes(currentFilter))); if(searchQuery){ const q = searchQuery.toLowerCase(); filtered = filtered.filter(s=> s.url.toLowerCase().includes(q) || s.type.toLowerCase().includes(q) || (s.validation?.resolution||'').toLowerCase().includes(q) || (s.validation?.contentType||'').toLowerCase().includes(q)); } countEl.textContent = `${filtered.length} stream${filtered.length!==1?'s':''} captured`; container.innerHTML=''; if (!filtered.length){ container.innerHTML = '<div class="empty-state"><p>No streams captured yet.</p><p class="hint">Start playback to capture manifests.</p></div>'; return; } filtered.forEach((stream,i)=> container.appendChild(createItem(stream,i))); }
  function createItem(stream,index){ const div = document.createElement('div'); div.className='stream-item'; let typeClass='other'; if(stream.type.includes('m3u8')) typeClass='m3u8'; else if(stream.type.includes('mpd')) typeClass='mpd'; else if(stream.type.includes('youtube')) typeClass='youtube'; else if(stream.type.includes('ts')) typeClass='ts'; else if(stream.isDRM) typeClass='drm'; const t = new Date(stream.timestamp).toLocaleTimeString(); const v = stream.validation || {}; const badge = buildBadge(v); const playlistInfo = v.playlistType? `<span>Type: ${v.playlistType}</span>`:''; const resInfo = v.resolution? `<span class="resolution">📺 ${v.resolution}</span>`:''; const bwInfo = v.bandwidth? `<span>${Math.round(v.bandwidth/1000)}k</span>`:''; const variantsInfo = v.variants && v.variants.length>1 ? `<span title="${v.variants.map(vv=>vv.res+' @ '+vv.bw).join(', ')}">${v.variants.length} variants</span>`:''; const ctInfo = v.contentType? `<span>${v.contentType.split(';')[0]}</span>`:''; const sizeInfo = v.sizeBytes? `<span>${humanSize(v.sizeBytes)}</span>`:''; const reasonInfo = v.reason? `<div class="warn">${escapeHtml(v.reason)}</div>`:''; div.innerHTML = `<div class="stream-header"><div><span class="stream-type ${typeClass}">${typeClass}</span>${stream.isDRM?'<span class="drm-badge">DRM</span>':''}${badge}</div><span style="font-size:11px;color:#999;">${t}</span></div><div class="stream-url" title="${stream.url}">${truncate(stream.url,80)}</div><div class="stream-meta"><span>Method: ${stream.method}</span>${playlistInfo}${resInfo}${bwInfo}${variantsInfo}${ctInfo}${sizeInfo}</div>${reasonInfo}<div class="stream-actions"><button class="open" data-index="${index}">▶ Open</button><button class="test" data-index="${index}">🧪 Revalidate</button><button class="copy" data-index="${index}">📋 URL</button><button class="copy-har" data-index="${index}">📋 HAR</button><button class="copy-full" data-index="${index}">📋 Full</button><button class="copy-command" data-index="${index}">💻 Command</button><button class="headers" data-index="${index}">📋 Headers</button><button class="details" data-index="${index}">🔍 JSON</button></div>`; return div; }
  function truncate(u,m){ if(u.length<=m) return u; const h=Math.floor(m/2); return u.substring(0,h)+'...'+u.substring(u.length-h); }
  async function copy(text){ try{ await navigator.clipboard.writeText(text); notify('✓ Copied'); }catch(e){ notify('✗ Copy failed', true); } }
  function notify(msg,err){ const n=document.createElement('div'); n.textContent=msg; n.style.cssText=`position:fixed;top:70px;right:16px;background:${err?'#f44336':'#4caf50'};color:#fff;padding:12px 20px;border-radius:6px;font-size:13px;z-index:1000;`; document.body.appendChild(n); setTimeout(()=>n.remove(),2000); }
  function buildBadge(v){ const s=v.status||'pending'; let color='#999',label='pending'; if(s==='ok'){color='#2e7d32';label='OK';} else if(s==='error'){color='#c62828';label='ERR';} else if(s==='unsupported'){color='#616161';label='N/A';} return `<span class="validation-badge" style="background:${color}">${label}</span>`; }
  function humanSize(bytes){ if(!bytes || isNaN(bytes)) return ''; const u=['B','KB','MB','GB']; let i=0,val=bytes; while(val>=1024 && i<u.length-1){ val/=1024; i++; } return `${val.toFixed(1)} ${u[i]}`; }
  function escapeHtml(str=''){ return str.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c])); }
  async function revalidate(stream){ const tab=await getCurrentTab(); notify('Validating...'); try{ const res=await api.runtime.sendMessage({ action:'revalidateStream', tabId:tab.id, url: stream.url }); if(res.success) notify('✓ Validation complete'); else notify('Validation failed', true); } catch(e){ notify('Validation error', true); } finally { loadStreams(); } }
  function genCommand(stream){ const url=stream.url; if(stream.type.includes('youtube')|| url.includes('googlevideo')) return `yt-dlp "${url}"`; if(stream.type.includes('m3u8')||url.includes('.m3u8')){ return genFFmpeg(stream); } if(stream.type.includes('mpd')||url.includes('.mpd')) return `yt-dlp "${url}"`; return genFFmpeg(stream); }
  function genFFmpeg(stream){ const url=stream.url; const h=stream.headers||{}; let cmd='ffmpeg'; const pairs=[]; for(const [k,v] of Object.entries(h)){ if(['host','content-length','connection'].includes(k.toLowerCase())) continue; pairs.push(`${k}: ${v}`); } if(pairs.length) cmd+=` -headers "${pairs.join('\\r\\n')}"`; cmd+=` -i "${url}" -c copy output.mp4`; return cmd; }
  function genCurl(stream){ const url=stream.url; const h=stream.headers||{}; let cmd=`curl "${url}"`; for(const [k,v] of Object.entries(h)){ const ev=v.replace(/"/g,'\\"'); cmd+=` \\\n  -H "${k}: ${ev}"`; } cmd+=' \\\n  -o output.file'; return cmd; }
  function genWget(stream){ const url=stream.url; const h=stream.headers||{}; let cmd=`wget "${url}"`; for(const [k,v] of Object.entries(h)){ const ev=v.replace(/"/g,'\\"'); cmd+=` \\\n  --header="${k}: ${ev}"`; } cmd+=' \\\n  -O output.file'; return cmd; }
  function genFull(stream){ const url=stream.url; const h=stream.headers||{}; let out=`# Stream URL\n${url}\n\n`; if(Object.keys(h).length){ out+='# Headers\n'; for(const [k,v] of Object.entries(h)) out+=`${k}: ${v}\n`; out+='\n'; } const v=stream.validation||{}; if(v.resolution) out+=`# Resolution: ${v.resolution}\n`; if(v.bandwidth) out+=`# Bandwidth: ${Math.round(v.bandwidth/1000)}k\n`; if(v.playlistType) out+=`# Type: ${v.playlistType}\n`; out+='\n'; out+=`# FFmpeg Command\n${genFFmpeg(stream)}\n\n`; out+=`# cURL Command\n${genCurl(stream)}\n\n`; out+=`# wget Command\n${genWget(stream)}\n`; return out; }
  document.getElementById('refresh').addEventListener('click', loadStreams);
  document.getElementById('clear').addEventListener('click', async ()=>{ const tab=await getCurrentTab(); await api.runtime.sendMessage({ action:'clearStreams', tabId: tab.id }); await loadStreams(); notify('✓ Cleared'); });
  document.getElementById('copy-all').addEventListener('click', async ()=>{ if(!streams.length){ notify('No streams to copy',true); return; } let out=`# Universal Stream Capture - Exported Commands\n# Total Streams: ${streams.length}\n# Generated: ${new Date().toLocaleString()}\n\n${'='.repeat(80)}\n\n`; streams.forEach((s,i)=>{ out+=`## Stream ${i+1}: ${s.type.toUpperCase()}\n${genFull(s)}\n${'='.repeat(80)}\n\n`; }); await copy(out); notify(`✓ Copied ${streams.length} stream${streams.length!==1?'s':''} with headers!`); });
  document.getElementById('export').addEventListener('click', async ()=>{ const dataStr = JSON.stringify(streams,null,2); const blob=new Blob([dataStr],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`streams_${Date.now()}.json`; a.click(); URL.revokeObjectURL(url); notify('✓ Exported'); });
  document.querySelectorAll('.filter-btn').forEach(btn => btn.addEventListener('click', () => { document.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); currentFilter=btn.dataset.filter; renderStreams(); }));
  document.getElementById('search-input').addEventListener('input', e => { searchQuery = e.target.value; renderStreams(); });
  document.getElementById('clear-search').addEventListener('click', () => { searchQuery = ''; document.getElementById('search-input').value = ''; renderStreams(); });
  document.getElementById('streams-list').addEventListener('click', async e => { const btn=e.target.closest('button'); if(!btn) return; const idx=parseInt(btn.dataset.index); const stream = streams.filter(s => currentFilter==='all'? true : (currentFilter==='drm'? s.isDRM : s.type.includes(currentFilter)))[idx]; if(!stream) return; if(btn.classList.contains('open')) api.tabs.create({ url: stream.url }); else if(btn.classList.contains('test')) await revalidate(stream); else if(btn.classList.contains('copy')) await copy(stream.url); else if(btn.classList.contains('copy-har')) { const tab=await getCurrentTab(); try{ const resp=await api.runtime.sendMessage({ action:'getStreamHAR', tabId: tab.id, url: stream.url }); if(resp && resp.har){ await copy(JSON.stringify(resp.har, null, 2)); notify('✓ HAR for this stream copied!'); } else { notify('No HAR data for this stream',true); } } catch(e){ notify('Failed to get HAR: '+e.message, true); } } else if(btn.classList.contains('copy-full')) { await copy(genFull(stream)); notify('✓ Full command with headers copied'); } else if(btn.classList.contains('copy-command')) await copy(genCommand(stream)); else if(btn.classList.contains('headers')) { const hs = Object.entries(stream.headers||{}).map(([k,v])=>`${k}: ${v}`).join('\n'); await copy(hs||'(no headers)'); } else if(btn.classList.contains('details')) { await copy(JSON.stringify(stream,null,2)); }
  });
  document.getElementById('streams-list').addEventListener('click', async e => { if(e.target.classList.contains('stream-url')) await copy(e.target.getAttribute('title')); });
  const adv = document.getElementById('advToggle'); api.storage.local.get({ usc_advanced:false }).then(d => adv.checked = !!d.usc_advanced); adv.addEventListener('change', ()=> { const enabled = adv.checked; api.storage.local.set({ usc_advanced: enabled }); api.runtime.sendMessage({ action:'uscToggleAdvanced', enabled }).catch(()=>{}); notify(enabled? 'Advanced ON' : 'Advanced OFF'); });
  loadStreams();
})();
